[workspace]
members = [ "rust_error", "rust_func", "rust_generic", "rust_lifetime", "rust_quick_sort","rust_study_day_1", "rust_study_day_2", "rust_study_day_3", "rust_study_day_4", "rust_study_day_5", "rust_trait"]
